name: deploy1

on:
  workflow_dispatch:
    inputs:
      name:
        description: name of the runner
        required: true
      name2:
        description: optional
        required: false

jobs:
  testing1:
    runs-on: ubuntu-latest
    steps:
      - name: print test1
        run: echo "test1"
      - name: shell commands
        run: |
          node -v
          npm -v
